name: Tests

on:
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:
    branches: [ 'master' ]

jobs:
  test:
    strategy:
      matrix:
        go_version: [ 1.18.x ]

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          # Module download cache, Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go_version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go_version }}-

      - name: Run test
        run: go test -race -json ./... > test.json

      - name: Annotate tests
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: test.json
